channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.3.2
  - psutil==7.1.0
  - pyarrow==17.0.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
